default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: my_app
  username: root
  password: 12345678
  host: 127.0.0.1
  port: 3306

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
